#!/usr/bin/env python3
"""Rebuild the single-file distribution from the ``app/`` package.

The maintained source of truth is the ``app/`` package plus ``main.py``. This
script flattens those modules into one self-contained, readable script,
``snyk_sbom_to_servicenow.py``, which is the customer deliverable.

For each source module it:
  * strips the module docstring, ``from __future__`` line, and imports,
  * hoists + de-duplicates third-party / stdlib imports to the top,
  * rewrites intra-package qualified calls (e.g. ``debug.log_variable(`` ->
    ``log_variable(``) into the bare names they'll have once flattened,

then prepends a shebang, PEP 723 inline dependency metadata (read from
``requirements.txt``), a module docstring, and ``__version__`` (read from
``app/__init__.py``).

Usage:
    python build_single_file.py            # writes snyk_sbom_to_servicenow.py
    python build_single_file.py --check    # verify the file is up to date (CI)
"""

from __future__ import annotations

import argparse
import ast
import py_compile
import re
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent
OUTPUT = REPO / "snyk_sbom_to_servicenow.py"

# Source modules, in dependency (definition) order.
MODULES: list[tuple[str, str]] = [
    ("app/errors.py", "Exit codes and error hierarchy"),
    ("app/logging.py", "Leveled logging (adds a TRACE level below DEBUG)"),
    ("app/utils/debug.py", "Variable-level debugging with centralized secret redaction"),
    ("app/utils/validators.py", "Validation helpers"),
    ("app/utils/http.py", "Reusable HTTP wrapper"),
    ("app/tls.py", "TLS: verify against the OS system trust store (like curl)"),
    ("app/config.py", "Configuration"),
    ("app/snyk_client.py", "Snyk SBOM generation"),
    ("app/sbom_file.py", "SBOM file persistence"),
    ("app/servicenow_client.py", "ServiceNow upload"),
    ("app/project_discovery.py", "Snyk project discovery (SNYK_API mode: Target / Org scope)"),
    ("app/sbom_service.py", "Single-project workflow: generate -> persist -> upload"),
    ("app/scope_manager.py", "Scope orchestration (SNYK_API mode)"),
    ("app/cli_mode.py", "CLI mode (SNYK_CLI): upload a Snyk-CLI-produced SBOM file"),
    ("main.py", "Entry point"),
]

# Intra-package qualified references -> bare names (all are calls / a def, so we
# anchor on a trailing "(" to avoid touching string literals such as the
# operation label "sbom_file.write_sbom").
REWRITES: list[tuple[str, str]] = [
    (r"\bdebug\.log_variable\(", "log_variable("),
    (r"\bdebug\.log_object\(", "log_object("),
    (r"\bdebug\.redact_headers\(", "redact_headers("),
    (r"\bdebug\.redact_value\(", "redact_value("),
    (r"\bhttp\.request\(", "http_request("),
    (r"\bproject_discovery\.discover_project\(", "discover_project("),
    (r"\bproject_discovery\.discover_projects_for_target\(", "discover_projects_for_target("),
    (r"\bproject_discovery\.discover_projects_for_org\(", "discover_projects_for_org("),
    (r"\bproject_discovery\.discover_targets\(", "discover_targets("),
    (r"\bsbom_file\.write_sbom\(", "write_sbom("),
    (r"\bdef request\(", "def http_request("),
]

TOP_DOCSTRING = '''"""Snyk SBOM -> ServiceNow upload utility (single-file distribution).

This is a self-contained build (generated by build_single_file.py) that combines
the entire application into one module for easy delivery. It exports a Software
Bill of Materials (SBOM) from Snyk (or accepts one produced by the Snyk CLI) and
uploads it to ServiceNow Vulnerability Response.

Two run modes (RUN_MODE):
  * SNYK_API (default) - call the Snyk REST API to generate SBOM(s) for a
    Project, Target, or whole Organization (SNOW_APPLICATION_SCOPE), then upload
    each to ServiceNow.
  * SNYK_CLI - upload an SBOM file you produced with the Snyk CLI, passed via
    --sbom-file-path.

Configuration is environment-variable driven (a local .env file is loaded when
present). See the bundled README / .env.example for the full variable list.

The dependency block above is PEP 723 inline script metadata: run with a
compatible runner to auto-provision dependencies, e.g.:
    uv run snyk_sbom_to_servicenow.py
    pipx run snyk_sbom_to_servicenow.py
Or install the dependencies yourself and use plain Python:
    pip install -r requirements.txt
    python snyk_sbom_to_servicenow.py

DO NOT EDIT THIS FILE BY HAND - it is generated from the app/ package by
build_single_file.py. Edit the modules under app/ and re-run the builder.

Exit codes:
    0  Success
    1  Configuration Error
    2  Authentication Failure
    3  SBOM Generation Failure
    4  ServiceNow Upload Failure
    5  Unexpected Exception
"""'''


def _read_version() -> str:
    tree = ast.parse((REPO / "app" / "__init__.py").read_text())
    for node in tree.body:
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "__version__":
                    return ast.literal_eval(node.value)
    raise SystemExit("Could not find __version__ in app/__init__.py")


def _read_dependencies() -> list[str]:
    deps: list[str] = []
    for line in (REPO / "requirements.txt").read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            deps.append(line)
    return deps


def _is_app_module(name: str | None) -> bool:
    return bool(name) and (name == "app" or name.startswith("app."))


def _process_module(rel_path: str) -> tuple[list[str], dict[str, set[str]], set[str]]:
    """Return (body_lines, from_imports, plain_imports) for a source module.

    - from_imports: {module: {names}}  (excludes __future__ and app.*)
    - plain_imports: {"mod" or "mod as alias"}  (excludes app.*)
    """
    src = (REPO / rel_path).read_text()
    tree = ast.parse(src)
    lines = src.splitlines()
    drop: set[int] = set()
    from_imports: dict[str, set[str]] = {}
    plain_imports: set[str] = set()

    # Drop the module docstring.
    if (
        tree.body
        and isinstance(tree.body[0], ast.Expr)
        and isinstance(tree.body[0].value, ast.Constant)
        and isinstance(tree.body[0].value.value, str)
    ):
        doc = tree.body[0]
        drop.update(range(doc.lineno, (doc.end_lineno or doc.lineno) + 1))

    for node in tree.body:
        if isinstance(node, ast.ImportFrom):
            drop.update(range(node.lineno, (node.end_lineno or node.lineno) + 1))
            if node.module == "__future__" or _is_app_module(node.module):
                continue
            names = from_imports.setdefault(node.module or "", set())
            for alias in node.names:
                names.add(alias.name + (f" as {alias.asname}" if alias.asname else ""))
        elif isinstance(node, ast.Import):
            drop.update(range(node.lineno, (node.end_lineno or node.lineno) + 1))
            for alias in node.names:
                if _is_app_module(alias.name):
                    continue
                plain_imports.add(alias.name + (f" as {alias.asname}" if alias.asname else ""))

    body = [line for i, line in enumerate(lines, start=1) if i not in drop]
    # Trim leading/trailing blank lines.
    while body and not body[0].strip():
        body.pop(0)
    while body and not body[-1].strip():
        body.pop()
    return body, from_imports, plain_imports


def build() -> str:
    version = _read_version()
    deps = _read_dependencies()

    all_from: dict[str, set[str]] = {}
    all_plain: set[str] = set()
    sections: list[tuple[str, list[str]]] = []

    for rel_path, title in MODULES:
        body, from_imports, plain_imports = _process_module(rel_path)
        for mod, names in from_imports.items():
            all_from.setdefault(mod, set()).update(names)
        all_plain.update(plain_imports)
        sections.append((title, body))

    # Apply intra-package rewrites to each section body.
    rewritten: list[tuple[str, str]] = []
    for title, body in sections:
        text = "\n".join(body)
        for pattern, repl in REWRITES:
            text = re.sub(pattern, repl, text)
        rewritten.append((title, text))

    # Build the import block.
    import_lines = ["from __future__ import annotations", ""]
    for mod in sorted(all_plain):
        import_lines.append(f"import {mod}")
    if all_plain:
        import_lines.append("")
    for mod in sorted(all_from):
        names = ", ".join(sorted(all_from[mod]))
        import_lines.append(f"from {mod} import {names}")

    # PEP 723 metadata block.
    pep723 = ["# /// script", "# requires-python = \">=3.12\"", "# dependencies = ["]
    for dep in deps:
        pep723.append(f'#     "{dep}",')
    pep723.append("# ]")
    pep723.append("# ///")

    banner = "# " + "\u2550" * 75

    out: list[str] = ["#!/usr/bin/env python3"]
    out.extend(pep723)
    out.append(TOP_DOCSTRING)
    out.append("")
    out.extend(import_lines)
    out.append("")
    out.append(f'__version__ = "{version}"')
    out.append("")

    for title, text in rewritten:
        out.append("")
        out.append(banner)
        out.append(f"# {title}")
        out.append(banner)
        out.append("")
        out.append(text)
        out.append("")

    return "\n".join(out).rstrip("\n") + "\n"


def _verify(content: str) -> None:
    """Byte-compile the generated content to catch syntax errors early."""
    with tempfile.NamedTemporaryFile("w", suffix=".py", delete=False, encoding="utf-8") as tmp:
        tmp.write(content)
        tmp_path = tmp.name
    py_compile.compile(tmp_path, doraise=True)
    Path(tmp_path).unlink(missing_ok=True)


def main() -> int:
    parser = argparse.ArgumentParser(description="Rebuild the single-file distribution.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify the committed single file matches a fresh build (exit 1 if stale).",
    )
    args = parser.parse_args()

    content = build()
    _verify(content)

    if args.check:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != content:
            print(f"{OUTPUT.name} is OUT OF DATE. Run: python build_single_file.py")
            return 1
        print(f"{OUTPUT.name} is up to date.")
        return 0

    OUTPUT.write_text(content)
    print(f"Wrote {OUTPUT.name} ({content.count(chr(10)) + 1} lines, version {_read_version()}).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
