#!/usr/bin/env python3
# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "requests==2.32.3",
#     "python-dotenv==1.0.1",
#     "truststore==0.10.4",
# ]
# ///
"""Snyk SBOM -> ServiceNow upload utility (single-file distribution).

This is a self-contained build (generated by build_single_file.py) that combines
the entire application into one module for easy delivery. It exports a Software
Bill of Materials (SBOM) from Snyk (or accepts one produced by the Snyk CLI) and
uploads it to ServiceNow Vulnerability Response.

Two run modes (RUN_MODE):
  * SNYK_API (default) - call the Snyk REST API to generate SBOM(s) for a
    Project, Target, or whole Organization (SNOW_APPLICATION_SCOPE), then upload
    each to ServiceNow.
  * SNYK_CLI - upload an SBOM file you produced with the Snyk CLI, passed via
    --sbom-file-path.

Configuration is environment-variable driven (a local .env file is loaded when
present). See the bundled README / .env.example for the full variable list.

The dependency block above is PEP 723 inline script metadata: run with a
compatible runner to auto-provision dependencies, e.g.:
    uv run snyk_sbom_to_servicenow.py
    pipx run snyk_sbom_to_servicenow.py
Or install the dependencies yourself and use plain Python:
    pip install -r requirements.txt
    python snyk_sbom_to_servicenow.py

DO NOT EDIT THIS FILE BY HAND - it is generated from the app/ package by
build_single_file.py. Edit the modules under app/ and re-run the builder.

Exit codes:
    0  Success
    1  Configuration Error
    2  Authentication Failure
    3  SBOM Generation Failure
    4  ServiceNow Upload Failure
    5  Unexpected Exception
"""

from __future__ import annotations

import argparse
import logging
import os
import pprint
import requests
import sys
import time

from collections.abc import Iterable, Mapping, Sequence, Set
from dataclasses import dataclass, replace
from datetime import datetime, timezone
from dotenv import dotenv_values
from pathlib import Path
from typing import Any, Final
from urllib.parse import urlsplit

__version__ = "1.0.0"


# ═══════════════════════════════════════════════════════════════════════════
# Exit codes and error hierarchy
# ═══════════════════════════════════════════════════════════════════════════

class ExitCode:
    """Documented process exit codes."""

    SUCCESS = 0
    CONFIG_ERROR = 1
    AUTH_FAILURE = 2
    SBOM_GENERATION_FAILURE = 3
    UPLOAD_FAILURE = 4
    UNEXPECTED = 5


class AppError(Exception):
    """Base class for all expected utility errors.

    Attributes carry enough context to produce an actionable message without
    leaking secrets (callers must never place secret values in these fields).
    """

    exit_code: int = ExitCode.UNEXPECTED

    def __init__(
        self,
        message: str,
        *,
        operation: str | None = None,
        url: str | None = None,
        status: int | None = None,
        parsed_message: str | None = None,
        next_step: str | None = None,
    ) -> None:
        super().__init__(message)
        self.message = message
        self.operation = operation
        self.url = url
        self.status = status
        self.parsed_message = parsed_message
        self.next_step = next_step

    def format_report(self) -> str:
        """Render a multi-line, human-readable error report."""
        lines = [self.message]
        if self.operation:
            lines.append(f"  Operation: {self.operation}")
        if self.url:
            lines.append(f"  URL: {self.url}")
        if self.status is not None:
            lines.append(f"  HTTP Status: {self.status}")
        if self.parsed_message:
            lines.append(f"  Detail: {self.parsed_message}")
        if self.next_step:
            lines.append(f"  Next step: {self.next_step}")
        return "\n".join(lines)


class ConfigError(AppError):
    """Missing or invalid configuration."""

    exit_code = ExitCode.CONFIG_ERROR


class AuthError(AppError):
    """Authentication/authorization failure against Snyk or ServiceNow."""

    exit_code = ExitCode.AUTH_FAILURE


class SbomGenerationError(AppError):
    """The SBOM could not be generated or the response was malformed."""

    exit_code = ExitCode.SBOM_GENERATION_FAILURE


class SbomUnsupportedError(AppError):
    """The project does not support SBOM export (Snyk returns HTTP 404).

    This is a distinct, non-fatal outcome: the orchestration layer records it as
    *skipped* rather than a failure so unsupported project types (SAST, IaC,
    container, ...) do not inflate the failure count or drive a failure exit code.
    """

    exit_code = ExitCode.SBOM_GENERATION_FAILURE


class UploadError(AppError):
    """The SBOM could not be uploaded to ServiceNow."""

    exit_code = ExitCode.UPLOAD_FAILURE


class HttpError(AppError):
    """Transport-level or non-2xx HTTP failure raised by the HTTP wrapper.

    Clients translate this into the appropriate domain error (e.g. ``AuthError``
    for 401/403) so orchestration can map it to the correct exit code.
    """

    exit_code = ExitCode.UNEXPECTED


# ═══════════════════════════════════════════════════════════════════════════
# Leveled logging (adds a TRACE level below DEBUG)
# ═══════════════════════════════════════════════════════════════════════════

TRACE: Final[int] = 5
_LEVEL_NAMES: Final[tuple[str, ...]] = ("ERROR", "WARNING", "INFO", "DEBUG", "TRACE")

_LOGGER_NAME: Final[str] = "snyk_sbom_to_servicenow"
_configured = False


def _install_trace_level() -> None:
    """Register the TRACE level and a ``logger.trace(...)`` convenience method."""
    if logging.getLevelName(TRACE) != "TRACE":
        logging.addLevelName(TRACE, "TRACE")

    def trace(self: logging.Logger, message: str, *args: object, **kwargs: object) -> None:
        if self.isEnabledFor(TRACE):
            self._log(TRACE, message, args, **kwargs)  # type: ignore[arg-type]

    if not hasattr(logging.Logger, "trace"):
        logging.Logger.trace = trace  # type: ignore[attr-defined]


def resolve_level(name: str | None) -> int:
    """Resolve a level name (case-insensitive) to a numeric logging level."""
    if not name:
        return logging.INFO
    candidate = name.strip().upper()
    if candidate == "TRACE":
        return TRACE
    return getattr(logging, candidate, logging.INFO)


def configure_logging(level_name: str | None = "INFO") -> logging.Logger:
    """Configure and return the application logger.

    Idempotent: repeated calls only update the level, never add handlers twice.
    """
    global _configured
    _install_trace_level()

    logger = logging.getLogger(_LOGGER_NAME)
    level = resolve_level(level_name)
    logger.setLevel(level)

    if not _configured:
        handler = logging.StreamHandler()
        handler.setFormatter(
            logging.Formatter(
                fmt="%(asctime)s | %(levelname)-7s | %(message)s",
                datefmt="%Y-%m-%d %H:%M:%S",
            )
        )
        logger.addHandler(handler)
        logger.propagate = False
        _configured = True

    for handler in logger.handlers:
        handler.setLevel(level)

    return logger


def get_logger() -> logging.Logger:
    """Return the shared application logger, configuring it if necessary."""
    logger = logging.getLogger(_LOGGER_NAME)
    if not _configured:
        return configure_logging()
    return logger


# ═══════════════════════════════════════════════════════════════════════════
# Variable-level debugging with centralized secret redaction
# ═══════════════════════════════════════════════════════════════════════════

MASK = "*" * 12

_SECRET_NAME_PATTERNS: tuple[str, ...] = (
    "token",
    "password",
    "passwd",
    "authorization",
    "auth",
    "secret",
    "api_key",
    "apikey",
    "access_token",
    "bearer",
)

_SUMMARY_TYPES = (Mapping, Set)


def _is_secret_name(name: str) -> bool:
    lowered = name.lower()
    return any(pattern in lowered for pattern in _SECRET_NAME_PATTERNS)


def redact_value(name: str, value: Any) -> Any:
    """Return a redacted representation of ``value`` if ``name`` looks secret.

    For an ``Authorization`` style header we preserve the scheme (e.g. ``Bearer``)
    and mask the credential so logs remain useful without leaking secrets.
    """
    if not _is_secret_name(name):
        return value

    if isinstance(value, str):
        parts = value.split(" ", 1)
        if len(parts) == 2 and parts[0].lower() in {"bearer", "token", "basic"}:
            return f"{parts[0]} {MASK}"
    return MASK


def redact_headers(headers: Mapping[str, Any] | None) -> dict[str, Any]:
    """Return a copy of ``headers`` with sensitive values masked."""
    if not headers:
        return {}
    return {key: redact_value(key, val) for key, val in headers.items()}


def _summarize(value: Any) -> str:
    """Produce a concise summary for collections and large scalars."""
    if isinstance(value, (bytes, bytearray)):
        return f"<{type(value).__name__} {len(value)} bytes>"
    if isinstance(value, str):
        if len(value) > 120:
            return f"<str len={len(value)}> {value[:100]!r}..."
        return repr(value)
    if isinstance(value, Mapping):
        return f"<dict keys={len(value)}: {sorted(map(str, value.keys()))}>"
    if isinstance(value, Set):
        return f"<{type(value).__name__} size={len(value)}>"
    if isinstance(value, Sequence):
        return f"<{type(value).__name__} len={len(value)}>"
    return repr(value)


def log_variable(name: str, value: Any) -> None:
    """Log a named variable at DEBUG level, redacted and summarized.

    - Secret-looking names are masked.
    - Collections and large values are summarized rather than dumped whole.
    """
    logger = get_logger()
    if not logger.isEnabledFor(10):  # logging.DEBUG
        return

    if _is_secret_name(name):
        rendered = redact_value(name, value if isinstance(value, str) else MASK)
        if not isinstance(value, str):
            rendered = MASK
    else:
        rendered = _summarize(value)
    logger.debug("%s: %s", name, rendered)


def log_object(value: Any, *, name: str | None = None) -> None:
    """Pretty-print an object at TRACE level.

    Mappings have secret-looking keys redacted before printing.
    """
    logger = get_logger()
    if not logger.isEnabledFor(TRACE):
        return

    to_print: Any = value
    if isinstance(value, Mapping):
        to_print = {key: redact_value(str(key), val) for key, val in value.items()}
    rendered = pprint.pformat(to_print, indent=2, width=100, sort_dicts=True)
    if name:
        logger.trace("%s:\n%s", name, rendered)  # type: ignore[attr-defined]
    else:
        logger.trace("%s", rendered)  # type: ignore[attr-defined]


# ═══════════════════════════════════════════════════════════════════════════
# Validation helpers
# ═══════════════════════════════════════════════════════════════════════════

_TRUTHY = {"true", "1", "yes", "on", "y", "t"}


def parse_bool(value: str | None, *, default: bool = False) -> bool:
    """Parse a truthy string (case-insensitive) into a bool."""
    if value is None:
        return default
    return value.strip().lower() in _TRUTHY


def missing_keys(source: Mapping[str, str | None], required: Iterable[str]) -> list[str]:
    """Return the required keys that are absent or empty in ``source``."""
    missing: list[str] = []
    for key in required:
        val = source.get(key)
        if val is None or str(val).strip() == "":
            missing.append(key)
    return missing


def is_nonempty_bytes(data: Any) -> bool:
    """True if ``data`` is a non-empty bytes-like or string payload."""
    if isinstance(data, (bytes, bytearray)):
        return len(data) > 0
    if isinstance(data, str):
        return len(data.strip()) > 0
    return False


# ═══════════════════════════════════════════════════════════════════════════
# Reusable HTTP wrapper
# ═══════════════════════════════════════════════════════════════════════════

@dataclass
class HttpResponse:
    """Normalized HTTP response returned by :func:`request`."""

    status: int
    headers: dict[str, str]
    content: bytes
    url: str
    elapsed_ms: float

    @property
    def text(self) -> str:
        return self.content.decode("utf-8", errors="replace")

    def json(self) -> Any:
        """Parse the body as JSON, raising ``HttpError`` on malformed content."""
        import json as _json

        try:
            return _json.loads(self.content.decode("utf-8"))
        except (ValueError, UnicodeDecodeError) as exc:
            raise HttpError(
                "Malformed response body (expected JSON).",
                url=self.url,
                status=self.status,
                parsed_message=str(exc),
                next_step="Verify the endpoint returns JSON and the API version is correct.",
            ) from exc


def _parse_error_message(content: bytes) -> str | None:
    """Best-effort extraction of an error message from a response body."""
    import json as _json

    try:
        payload = _json.loads(content.decode("utf-8"))
    except (ValueError, UnicodeDecodeError):
        text = content.decode("utf-8", errors="replace").strip()
        return text[:500] or None

    if isinstance(payload, Mapping):
        for key in ("error", "message", "detail", "title"):
            if key in payload and payload[key]:
                return str(payload[key])
        if "errors" in payload and payload["errors"]:
            return str(payload["errors"])
    return None


def http_request(
    method: str,
    url: str,
    *,
    operation: str,
    headers: Mapping[str, str] | None = None,
    params: Mapping[str, Any] | None = None,
    data: bytes | str | None = None,
    json_body: Any = None,
    timeout: float = 60.0,
    verify: bool | str = True,
) -> HttpResponse:
    """Perform an HTTP request and return a normalized response.

    Args:
        verify: Passed through to ``requests`` — ``True``/``False`` or a path to
            a CA bundle. TLS verification uses the OS trust store when it has
            been enabled via :mod:`app.tls`.

    Raises:
        HttpError: on transport failure, timeout, or a non-2xx status.
    """
    logger = get_logger()
    logger.debug("HTTP %s %s", method.upper(), url)
    log_variable("Request Headers", redact_headers(headers))
    if params:
        log_variable("Query Params", dict(params))
    # TRACE: full request detail (body redaction is the caller's responsibility
    # for secret payloads; SBOM bodies are not secret).
    logger.trace("Request body bytes: %s", len(data) if data else 0)  # type: ignore[attr-defined]

    start = time.perf_counter()
    try:
        resp = requests.request(
            method=method,
            url=url,
            headers=dict(headers) if headers else None,
            params=dict(params) if params else None,
            data=data,
            json=json_body,
            timeout=timeout,
            verify=verify,
        )
    except requests.Timeout as exc:
        raise HttpError(
            "Request timed out.",
            operation=operation,
            url=url,
            parsed_message=str(exc),
            next_step=f"Increase HTTP_TIMEOUT_SECONDS (current {timeout}s) or check connectivity.",
        ) from exc
    except requests.RequestException as exc:
        raise HttpError(
            "HTTP transport error.",
            operation=operation,
            url=url,
            parsed_message=str(exc),
            next_step="Verify network connectivity and the target URL.",
        ) from exc

    elapsed_ms = (time.perf_counter() - start) * 1000.0
    normalized = HttpResponse(
        status=resp.status_code,
        headers=dict(resp.headers),
        content=resp.content,
        url=resp.url,
        elapsed_ms=elapsed_ms,
    )

    logger.debug("HTTP %s -> %s (%.1f ms)", method.upper(), resp.status_code, elapsed_ms)
    log_variable("Response Headers", normalized.headers)
    logger.trace("Response body:\n%s", normalized.text[:2000])  # type: ignore[attr-defined]

    if not (200 <= resp.status_code < 300):
        raise HttpError(
            f"HTTP request failed with status {resp.status_code}.",
            operation=operation,
            url=normalized.url,
            status=resp.status_code,
            parsed_message=_parse_error_message(normalized.content),
            next_step="Inspect the status and detail above; verify credentials and request shape.",
        )

    return normalized


# ═══════════════════════════════════════════════════════════════════════════
# TLS: verify against the OS system trust store (like curl)
# ═══════════════════════════════════════════════════════════════════════════

_injected = False


def enable_system_trust() -> bool:
    """Route TLS verification through the OS trust store (idempotent).

    Returns True if the system trust store is now in use, False if ``truststore``
    is unavailable (in which case the default ``certifi`` behavior remains).
    """
    global _injected
    if _injected:
        return True

    logger = get_logger()
    try:
        import truststore
    except ImportError:
        logger.debug("truststore not installed; using certifi CA bundle for TLS.")
        return False

    truststore.inject_into_ssl()
    _injected = True
    logger.debug("TLS verification is using the OS system trust store (truststore).")
    return True


# ═══════════════════════════════════════════════════════════════════════════
# Configuration
# ═══════════════════════════════════════════════════════════════════════════

# Run mode: how the SBOM is obtained.
MODE_API: Final[str] = "SNYK_API"
MODE_CLI: Final[str] = "SNYK_CLI"
VALID_RUN_MODES: Final[tuple[str, ...]] = (MODE_API, MODE_CLI)
DEFAULT_RUN_MODE: Final[str] = MODE_API

# Processing scope: how many Snyk projects a single run covers (API mode only).
SCOPE_PROJECT: Final[str] = "SNYK_PROJECT"
SCOPE_TARGET: Final[str] = "SNYK_TARGET"
SCOPE_ORG: Final[str] = "SNYK_ORG"
VALID_SCOPES: Final[tuple[str, ...]] = (SCOPE_PROJECT, SCOPE_TARGET, SCOPE_ORG)
DEFAULT_SCOPE: Final[str] = SCOPE_PROJECT

# ServiceNow variables are required in every run mode (they are the upload target).
SNOW_REQUIRED_VARS: Final[tuple[str, ...]] = (
    "SNOW_INSTANCE_SUBDOMAIN",
    "SNOW_ACCESS_TOKEN",
    "SNOW_BUSINESS_APPLICATION_ID",
)

# Snyk API variables are required only in SNYK_API mode.
API_REQUIRED_VARS: Final[tuple[str, ...]] = (
    "SNYK_API_TOKEN",
    "SNYK_ORG_ID",
)

# Additional Snyk identifiers required per scope (SNYK_API mode only).
SCOPE_REQUIRED_VARS: Final[dict[str, tuple[str, ...]]] = {
    SCOPE_PROJECT: ("SNYK_TARGET_ID", "SNYK_PROJECT_ID"),
    SCOPE_TARGET: ("SNYK_TARGET_ID",),
    SCOPE_ORG: (),
}

DEFAULT_SBOM_FORMAT: Final[str] = "cyclonedx1.6+json"
DEFAULT_SNYK_BASE_URL: Final[str] = "https://api.snyk.io/rest"
DEFAULT_DEBUG_LEVEL: Final[str] = "INFO"
DEFAULT_HTTP_TIMEOUT: Final[float] = 60.0

# Values copied straight from .env.example still carry this prefix. Running with
# them almost always means the .env was not filled in (or not saved), so we fail
# fast with a clear message instead of emitting a confusing upstream 404/401.
PLACEHOLDER_PREFIX: Final[str] = "MY_"


@dataclass(frozen=True)
class Config:
    """Immutable runtime configuration."""

    snyk_api_token: str
    snyk_org_id: str
    snyk_target_id: str
    snyk_project_id: str
    snyk_base_url: str
    snyk_rest_api_version: str | None
    snyk_sbom_format: str

    snow_instance_subdomain: str
    snow_access_token: str
    snow_business_application_id: str
    snow_application_scope: str

    run_mode: str

    debug_level: str
    api_dry_run: bool
    http_timeout_seconds: float

    ssl_verify: bool
    ca_bundle: str | None

    @property
    def snow_base_url(self) -> str:
        return f"https://{self.snow_instance_subdomain}.service-now.com"

    @property
    def sbom_source(self) -> str:
        """The ServiceNow ``sbomSource`` query value for the current run mode."""
        return "SnykCLI" if self.run_mode == MODE_CLI else "SnykAPI"

    @property
    def tls_verify(self) -> bool | str:
        """The value to pass to ``requests`` as ``verify``.

        A CA bundle path takes precedence; otherwise a boolean toggle. TLS
        verification defaults to on (and uses the OS trust store when enabled
        via :mod:`app.tls`).
        """
        if self.ca_bundle:
            return self.ca_bundle
        return self.ssl_verify


def _merged_env() -> dict[str, str | None]:
    """Merge ``.env`` values with the process environment (env wins)."""
    merged: dict[str, str | None] = dict(dotenv_values())
    for key, value in os.environ.items():
        merged[key] = value
    return merged


def _get(source: dict[str, str | None], key: str, default: str | None = None) -> str | None:
    value = source.get(key)
    if value is None or str(value).strip() == "":
        return default
    return str(value).strip()


def load_config() -> Config:
    """Load configuration, validating required variables and applying defaults.

    Raises:
        ConfigError: if any required variable is missing/empty or a numeric
            option cannot be parsed.
    """
    source = _merged_env()

    run_mode = (_get(source, "RUN_MODE", DEFAULT_RUN_MODE) or DEFAULT_RUN_MODE).upper()
    if run_mode not in VALID_RUN_MODES:
        raise ConfigError(
            f"Invalid RUN_MODE: {run_mode!r}.",
            operation="load_config",
            next_step="Set RUN_MODE to one of: " + ", ".join(VALID_RUN_MODES) + ".",
        )

    scope = (_get(source, "SNOW_APPLICATION_SCOPE", DEFAULT_SCOPE) or DEFAULT_SCOPE).upper()
    if scope not in VALID_SCOPES:
        raise ConfigError(
            f"Invalid SNOW_APPLICATION_SCOPE: {scope!r}.",
            operation="load_config",
            next_step="Set SNOW_APPLICATION_SCOPE to one of: " + ", ".join(VALID_SCOPES) + ".",
        )

    # ServiceNow variables are always required; Snyk API + scope variables are
    # only required in SNYK_API mode (SNYK_CLI uploads a provided file instead).
    required = SNOW_REQUIRED_VARS
    if run_mode == MODE_API:
        required = required + API_REQUIRED_VARS + SCOPE_REQUIRED_VARS[scope]
    missing = missing_keys(source, required)
    if missing:
        raise ConfigError(
            f"Missing required configuration variable(s) for RUN_MODE {run_mode}"
            + (f" / scope {scope}" if run_mode == MODE_API else "")
            + ": " + ", ".join(missing),
            operation="load_config",
            next_step=(
                "Set the listed variable(s) in your .env file or environment. "
                "See .env.example for the full list."
            ),
        )

    timeout_raw = _get(source, "HTTP_TIMEOUT_SECONDS")
    try:
        http_timeout = float(timeout_raw) if timeout_raw else DEFAULT_HTTP_TIMEOUT
    except ValueError as exc:
        raise ConfigError(
            f"HTTP_TIMEOUT_SECONDS must be a number, got: {timeout_raw!r}",
            operation="load_config",
            next_step="Set HTTP_TIMEOUT_SECONDS to a numeric value (seconds).",
        ) from exc

    config = Config(
        snyk_api_token=_get(source, "SNYK_API_TOKEN") or "",
        snyk_org_id=_get(source, "SNYK_ORG_ID") or "",
        snyk_target_id=_get(source, "SNYK_TARGET_ID") or "",
        snyk_project_id=_get(source, "SNYK_PROJECT_ID") or "",
        snyk_base_url=_get(source, "SNYK_BASE_URL", DEFAULT_SNYK_BASE_URL) or DEFAULT_SNYK_BASE_URL,
        snyk_rest_api_version=_get(source, "SNYK_REST_API_VERSION"),
        snyk_sbom_format=_get(source, "SNYK_SBOM_FORMAT", DEFAULT_SBOM_FORMAT) or DEFAULT_SBOM_FORMAT,
        snow_instance_subdomain=_get(source, "SNOW_INSTANCE_SUBDOMAIN") or "",
        snow_access_token=_get(source, "SNOW_ACCESS_TOKEN") or "",
        snow_business_application_id=_get(source, "SNOW_BUSINESS_APPLICATION_ID") or "",
        snow_application_scope=scope,
        run_mode=run_mode,
        debug_level=_get(source, "DEBUG_LEVEL", DEFAULT_DEBUG_LEVEL) or DEFAULT_DEBUG_LEVEL,
        api_dry_run=parse_bool(_get(source, "API_DRY_RUN"), default=False),
        http_timeout_seconds=http_timeout,
        ssl_verify=parse_bool(_get(source, "SSL_VERIFY"), default=True),
        ca_bundle=_get(source, "CA_BUNDLE"),
    )

    _reject_placeholders(config)
    return config


def _reject_placeholders(config: Config) -> None:
    """Fail fast when configuration still holds ``.env.example`` placeholders.

    Only variables actually used by the current run mode are checked: the Snyk
    API credentials (and scope identifiers) are checked only in SNYK_API mode,
    while the ServiceNow credentials are checked whenever an upload will occur
    (always in CLI mode; in API mode unless it is a dry run).
    """
    checks: list[tuple[str, str]] = []
    if config.run_mode == MODE_API:
        checks.extend(
            [
                ("SNYK_API_TOKEN", config.snyk_api_token),
                ("SNYK_ORG_ID", config.snyk_org_id),
            ]
        )
        scope_vars = {
            "SNYK_TARGET_ID": config.snyk_target_id,
            "SNYK_PROJECT_ID": config.snyk_project_id,
        }
        for name in SCOPE_REQUIRED_VARS[config.snow_application_scope]:
            checks.append((name, scope_vars[name]))

    upload_will_happen = not (config.run_mode == MODE_API and config.api_dry_run)
    if upload_will_happen:
        checks.extend(
            [
                ("SNOW_INSTANCE_SUBDOMAIN", config.snow_instance_subdomain),
                ("SNOW_ACCESS_TOKEN", config.snow_access_token),
                ("SNOW_BUSINESS_APPLICATION_ID", config.snow_business_application_id),
            ]
        )

    placeholders = [name for name, value in checks if value.startswith(PLACEHOLDER_PREFIX)]
    if placeholders:
        raise ConfigError(
            "Configuration still contains placeholder value(s): " + ", ".join(placeholders),
            operation="load_config",
            next_step=(
                "Replace the placeholder(s) in your .env with real values and SAVE the file. "
                "Unsaved editor changes are not read from disk."
            ),
        )


# ═══════════════════════════════════════════════════════════════════════════
# Snyk SBOM generation
# ═══════════════════════════════════════════════════════════════════════════

@dataclass
class SbomDocument:
    """A generated SBOM held in memory for upload."""

    content: bytes
    content_type: str
    sbom_format: str

    @property
    def size(self) -> int:
        return len(self.content)


class SnykClient:
    """Thin client over the Snyk REST SBOM endpoint."""

    def __init__(self, config: Config) -> None:
        self._config = config
        self._logger = get_logger()

    def _headers(self) -> dict[str, str]:
        return {
            "Authorization": f"token {self._config.snyk_api_token}",
            "Accept": "application/vnd.api+json",
        }

    def _sbom_url(self) -> str:
        base = self._config.snyk_base_url.rstrip("/")
        return (
            f"{base}/orgs/{self._config.snyk_org_id}"
            f"/projects/{self._config.snyk_project_id}/sbom"
        )

    def generate_sbom(self) -> SbomDocument:
        """Generate an SBOM for the configured project.

        Raises:
            AuthError: on 401/403 from Snyk.
            SbomGenerationError: on other failures or an empty/malformed body.
        """
        url = self._sbom_url()
        params: dict[str, str] = {"format": self._config.snyk_sbom_format}
        if self._config.snyk_rest_api_version:
            params["version"] = self._config.snyk_rest_api_version

        self._logger.info("Generating SBOM")
        log_variable("SNYK_ORG_ID", self._config.snyk_org_id)
        log_variable("SNYK_PROJECT_ID", self._config.snyk_project_id)
        log_variable("SBOM_FORMAT", self._config.snyk_sbom_format)

        try:
            resp = http_request(
                "GET",
                url,
                operation="snyk.generate_sbom",
                headers=self._headers(),
                params=params,
                timeout=self._config.http_timeout_seconds,
                verify=self._config.tls_verify,
            )
        except HttpError as exc:
            if exc.status in (401, 403):
                raise AuthError(
                    "Snyk authentication failed.",
                    operation=exc.operation,
                    url=exc.url,
                    status=exc.status,
                    parsed_message=exc.parsed_message,
                    next_step="Verify SNYK_API_TOKEN and that it can access SNYK_ORG_ID.",
                ) from exc
            if exc.status == 404:
                raise SbomUnsupportedError(
                    "SBOM is not supported for this project (HTTP 404).",
                    operation=exc.operation,
                    url=exc.url,
                    status=exc.status,
                    parsed_message=exc.parsed_message,
                    next_step=(
                        "This project type does not support SBOM export; it will be skipped. "
                        "If unexpected, verify SNYK_PROJECT_ID is correct."
                    ),
                ) from exc
            raise SbomGenerationError(
                "Failed to generate SBOM from Snyk.",
                operation=exc.operation,
                url=exc.url,
                status=exc.status,
                parsed_message=exc.parsed_message,
                next_step=(
                    "Verify SNYK_PROJECT_ID, SNYK_SBOM_FORMAT, and SNYK_REST_API_VERSION "
                    "are valid for this org."
                ),
            ) from exc

        if not is_nonempty_bytes(resp.content):
            raise SbomGenerationError(
                "Snyk returned an empty SBOM document.",
                operation="snyk.generate_sbom",
                url=resp.url,
                status=resp.status,
                next_step="Confirm the project has been scanned and supports SBOM generation.",
            )

        content_type = resp.headers.get("Content-Type", "application/octet-stream")
        document = SbomDocument(
            content=resp.content,
            content_type=content_type,
            sbom_format=self._config.snyk_sbom_format,
        )

        self._logger.info("SBOM generated (%s, %d bytes)", document.sbom_format, document.size)
        log_variable("SBOM Content-Type", content_type)
        log_variable("Payload Size", document.size)
        return document


# ═══════════════════════════════════════════════════════════════════════════
# SBOM file persistence
# ═══════════════════════════════════════════════════════════════════════════

def _timestamp() -> str:
    """Return a filename-safe UTC timestamp: ``YYYYMMDDTHHMMSSZ``."""
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def build_filename(project_id: str, *, timestamp: str | None = None) -> str:
    """Build the SBOM filename ``<timestamp>-snyk-<project_id>-sbom.json``."""
    ts = timestamp or _timestamp()
    return f"{ts}-snyk-{project_id}-sbom.json"


def write_sbom(document: SbomDocument, project_id: str, root: Path | None = None) -> Path:
    """Write the SBOM bytes, unmodified, to a timestamped file in ``root``.

    Args:
        document: The generated SBOM to persist.
        project_id: Snyk project id, embedded in the filename.
        root: Target directory (defaults to the current working directory).

    Returns:
        The absolute path of the written file.

    Raises:
        SbomGenerationError: if the file cannot be written.
    """
    logger = get_logger()
    target_dir = (root or Path.cwd()).resolve()
    path = target_dir / build_filename(project_id)

    try:
        path.write_bytes(document.content)
    except OSError as exc:
        raise SbomGenerationError(
            "Failed to write SBOM file to disk.",
            operation="sbom_file.write_sbom",
            url=str(path),
            parsed_message=str(exc),
            next_step="Verify write permissions and available disk space for the target directory.",
        ) from exc

    logger.info("SBOM written to %s (%d bytes)", path, document.size)
    return path


# ═══════════════════════════════════════════════════════════════════════════
# ServiceNow upload
# ═══════════════════════════════════════════════════════════════════════════

UPLOAD_PATH = "api/sbom/core/upload"


class ServiceNowClient:
    """Thin client over the ServiceNow SBOM upload API."""

    def __init__(self, config: Config) -> None:
        self._config = config
        self._logger = get_logger()

    def _headers(self) -> dict[str, str]:
        return {
            "Authorization": f"Bearer {self._config.snow_access_token}",
            "Content-Type": "application/json",
            "Accept": "application/json",
        }

    def _upload_url(self) -> str:
        return f"{self._config.snow_base_url}/{UPLOAD_PATH}"

    def upload_sbom(self, sbom_path: Path) -> dict:
        """Upload the persisted SBOM file to ServiceNow.

        The file bytes are sent unmodified (``--data-binary @file``).

        Raises:
            AuthError: on 401/403 from ServiceNow.
            UploadError: if the file cannot be read, or on other failures /
                malformed responses.
        """
        url = self._upload_url()
        params = {
            "businessApplicationId": self._config.snow_business_application_id,
            "sbomSource": self._config.sbom_source,
        }

        try:
            payload = Path(sbom_path).read_bytes()
        except OSError as exc:
            raise UploadError(
                "Failed to read the persisted SBOM file for upload.",
                operation="servicenow.upload_sbom",
                url=str(sbom_path),
                parsed_message=str(exc),
                next_step="Verify the SBOM file exists and is readable.",
            ) from exc

        self._logger.info("Uploading SBOM to ServiceNow")
        log_variable("Upload URL", url)
        log_variable("SNOW_BUSINESS_APPLICATION_ID", self._config.snow_business_application_id)
        log_variable("SBOM File", str(sbom_path))
        log_variable("Payload Size", len(payload))

        try:
            resp = http_request(
                "POST",
                url,
                operation="servicenow.upload_sbom",
                headers=self._headers(),
                params=params,
                data=payload,
                timeout=self._config.http_timeout_seconds,
                verify=self._config.tls_verify,
            )
        except HttpError as exc:
            if exc.status in (401, 403):
                raise AuthError(
                    "ServiceNow authentication failed.",
                    operation=exc.operation,
                    url=exc.url,
                    status=exc.status,
                    parsed_message=exc.parsed_message,
                    next_step="Verify SNOW_ACCESS_TOKEN and that it has SBOM upload permission.",
                ) from exc
            raise UploadError(
                "Failed to upload SBOM to ServiceNow.",
                operation=exc.operation,
                url=exc.url,
                status=exc.status,
                parsed_message=exc.parsed_message,
                next_step=(
                    "Verify SNOW_INSTANCE_SUBDOMAIN and SNOW_BUSINESS_APPLICATION_ID."
                ),
            ) from exc

        try:
            body = resp.json() if resp.content else {}
        except HttpError:
            # A non-JSON 2xx response is acceptable for some endpoints.
            body = {"raw": resp.text[:500]}

        self._logger.info("SBOM uploaded to ServiceNow (status %s)", resp.status)
        log_object(body, name="ServiceNow Response")
        return body if isinstance(body, dict) else {"response": body}


# ═══════════════════════════════════════════════════════════════════════════
# Snyk project discovery (SNYK_API mode: Target / Org scope)
# ═══════════════════════════════════════════════════════════════════════════

_PAGE_LIMIT = 100
_MAX_PAGES = 1000  # safety valve against pathological pagination loops


@dataclass(frozen=True)
class Project:
    """A discovered Snyk project."""

    org_id: str
    target_id: str
    project_id: str
    name: str


@dataclass(frozen=True)
class Target:
    """A discovered Snyk target."""

    target_id: str
    name: str


def _headers(config: Config) -> dict[str, str]:
    return {
        "Authorization": f"token {config.snyk_api_token}",
        "Accept": "application/vnd.api+json",
    }


def _api_host(config: Config) -> str:
    parts = urlsplit(config.snyk_base_url)
    return f"{parts.scheme}://{parts.netloc}"


def _next_url(host: str, links: Any) -> str | None:
    """Resolve the ``links.next`` cursor (relative or absolute) to a full URL."""
    if not isinstance(links, dict):
        return None
    nxt = links.get("next")
    if not nxt or not isinstance(nxt, str):
        return None
    if nxt.startswith("http://") or nxt.startswith("https://"):
        return nxt
    return host + ("" if nxt.startswith("/") else "/") + nxt


def _paginate(config: Config, path: str, params: dict[str, str], operation: str) -> list[dict]:
    """Fetch every page of a Snyk REST list endpoint, returning all data items.

    Args:
        path: Path appended to the configured base URL for the first request
            (e.g. ``/orgs/<org>/projects``).
        params: Query parameters for the first request; subsequent pages follow
            the ``links.next`` cursor which already carries its own query.

    Raises:
        AuthError: on 401/403 (fatal).
        SbomGenerationError: on other discovery HTTP or parsing failures.
    """
    logger = get_logger()
    host = _api_host(config)
    base = config.snyk_base_url.rstrip("/")
    url: str | None = f"{base}{path}"
    first_params: dict[str, str] | None = dict(params)

    items: list[dict] = []
    pages = 0
    while url and pages < _MAX_PAGES:
        pages += 1
        try:
            resp = http_request(
                "GET",
                url,
                operation=operation,
                headers=_headers(config),
                params=first_params,
                timeout=config.http_timeout_seconds,
                verify=config.tls_verify,
            )
            payload = resp.json()
        except HttpError as exc:
            if exc.status in (401, 403):
                raise AuthError(
                    "Snyk authentication failed during discovery.",
                    operation=exc.operation or operation,
                    url=exc.url or url,
                    status=exc.status,
                    parsed_message=exc.parsed_message,
                    next_step="Verify SNYK_API_TOKEN and that it can access SNYK_ORG_ID.",
                ) from exc
            raise SbomGenerationError(
                "Failed to enumerate Snyk resources.",
                operation=exc.operation or operation,
                url=exc.url or url,
                status=exc.status,
                parsed_message=exc.parsed_message,
                next_step="Verify SNYK_ORG_ID / SNYK_TARGET_ID and the Snyk REST API version.",
            ) from exc

        data = payload.get("data", []) if isinstance(payload, dict) else []
        if isinstance(data, list):
            items.extend(d for d in data if isinstance(d, dict))

        url = _next_url(host, payload.get("links") if isinstance(payload, dict) else None)
        first_params = None  # the next link already includes query params

    logger.debug("Discovery %s returned %d item(s) over %d page(s)", operation, len(items), pages)
    return items


def _project_from_item(config: Config, item: dict) -> Project:
    attrs = item.get("attributes", {}) if isinstance(item.get("attributes"), dict) else {}
    project_id = str(item.get("id", ""))
    name = str(attrs.get("name") or project_id)

    target_id = ""
    rels = item.get("relationships")
    if isinstance(rels, dict):
        target = rels.get("target")
        if isinstance(target, dict):
            tdata = target.get("data")
            if isinstance(tdata, dict):
                target_id = str(tdata.get("id", ""))

    return Project(
        org_id=config.snyk_org_id,
        target_id=target_id or config.snyk_target_id,
        project_id=project_id,
        name=name,
    )


def discover_project(config: Config) -> list[Project]:
    """Return exactly the single configured project (no API call)."""
    return [
        Project(
            org_id=config.snyk_org_id,
            target_id=config.snyk_target_id,
            project_id=config.snyk_project_id,
            name=config.snyk_project_id,
        )
    ]


def _project_list_params(config: Config, *, target_id: str | None = None) -> dict[str, str]:
    params: dict[str, str] = {"limit": str(_PAGE_LIMIT)}
    if config.snyk_rest_api_version:
        params["version"] = config.snyk_rest_api_version
    if target_id:
        params["target_id"] = target_id
    return params


def discover_projects_for_target(config: Config) -> list[Project]:
    """Enumerate every project associated with ``SNYK_TARGET_ID``."""
    log_variable("SNYK_TARGET_ID", config.snyk_target_id)
    items = _paginate(
        config,
        f"/orgs/{config.snyk_org_id}/projects",
        _project_list_params(config, target_id=config.snyk_target_id),
        operation="snyk.discover_projects_for_target",
    )
    return [_project_from_item(config, i) for i in items]


def discover_projects_for_org(config: Config) -> list[Project]:
    """Enumerate every project across all targets in ``SNYK_ORG_ID``."""
    items = _paginate(
        config,
        f"/orgs/{config.snyk_org_id}/projects",
        _project_list_params(config),
        operation="snyk.discover_projects_for_org",
    )
    return [_project_from_item(config, i) for i in items]


def discover_targets(config: Config) -> list[Target]:
    """Enumerate every target in ``SNYK_ORG_ID`` (used for summary counts)."""
    params: dict[str, str] = {"limit": str(_PAGE_LIMIT)}
    if config.snyk_rest_api_version:
        params["version"] = config.snyk_rest_api_version
    items = _paginate(
        config,
        f"/orgs/{config.snyk_org_id}/targets",
        params,
        operation="snyk.discover_targets",
    )
    targets: list[Target] = []
    for item in items:
        attrs = item.get("attributes", {}) if isinstance(item.get("attributes"), dict) else {}
        name = str(attrs.get("display_name") or attrs.get("displayName") or attrs.get("url") or item.get("id", ""))
        targets.append(Target(target_id=str(item.get("id", "")), name=name))
    return targets


# ═══════════════════════════════════════════════════════════════════════════
# Single-project workflow: generate -> persist -> upload
# ═══════════════════════════════════════════════════════════════════════════

@dataclass
class RunResult:
    """Outcome of a full run."""

    document: SbomDocument
    sbom_path: Path
    uploaded: bool
    skipped_reason: str | None = None
    response: dict | None = None


class SbomService:
    """Orchestrates SBOM export from Snyk and upload to ServiceNow."""

    def __init__(
        self,
        config: Config,
        snyk_client: SnykClient | None = None,
        servicenow_client: ServiceNowClient | None = None,
    ) -> None:
        self._config = config
        self._logger = get_logger()
        self._snyk = snyk_client or SnykClient(config)
        self._servicenow = servicenow_client or ServiceNowClient(config)

    def run(self) -> RunResult:
        """Generate the SBOM, persist it to a file, then upload it (unless dry-run)."""
        document = self._snyk.generate_sbom()
        sbom_path = write_sbom(document, self._config.snyk_project_id)

        if self._config.api_dry_run:
            reason = "API_DRY_RUN enabled: skipping ServiceNow upload."
            self._logger.info(reason)
            return RunResult(
                document=document,
                sbom_path=sbom_path,
                uploaded=False,
                skipped_reason=reason,
            )

        response = self._servicenow.upload_sbom(sbom_path)
        return RunResult(
            document=document,
            sbom_path=sbom_path,
            uploaded=True,
            response=response,
        )


# ═══════════════════════════════════════════════════════════════════════════
# Scope orchestration (SNYK_API mode)
# ═══════════════════════════════════════════════════════════════════════════

@dataclass
class ProjectResult:
    """Outcome of processing a single project."""

    project: Project
    generated: bool
    uploaded: bool
    ok: bool
    elapsed_s: float
    skipped: bool = False
    error: str | None = None


@dataclass
class ScopeSummary:
    """Aggregate outcome of a scoped run."""

    scope: str
    dry_run: bool
    projects_discovered: int
    sboms_generated: int
    succeeded: int
    failed: int
    elapsed_s: float
    skipped: int = 0
    targets_discovered: int | None = None

    @property
    def exit_code(self) -> int:
        """Exit 4 only for genuine failures; skips never trigger a failure code."""
        return ExitCode.SUCCESS if self.failed == 0 else ExitCode.UPLOAD_FAILURE

    def format_report(self) -> str:
        def fmt_elapsed(seconds: float) -> str:
            minutes, secs = divmod(int(seconds), 60)
            return f"{minutes}m {secs}s" if minutes else f"{secs}s"

        lines = [
            "Processing summary:",
            f"  Scope: {self.scope}",
        ]
        if self.targets_discovered is not None:
            lines.append(f"  Targets discovered: {self.targets_discovered}")
        lines.extend(
            [
                f"  Projects discovered: {self.projects_discovered}",
                f"  SBOMs generated: {self.sboms_generated}",
                f"  {'Skipped (dry-run)' if self.dry_run else 'Successful uploads'}: {self.succeeded}",
                f"  Skipped (unsupported): {self.skipped}",
                f"  Failed: {self.failed}",
                f"  Elapsed time: {fmt_elapsed(self.elapsed_s)}",
            ]
        )
        return "\n".join(lines)


def _discover(config: Config) -> tuple[list[Project], int | None]:
    """Discover projects for the scope; returns (projects, targets_discovered)."""
    scope = config.snow_application_scope
    if scope == SCOPE_PROJECT:
        return discover_project(config), None
    if scope == SCOPE_TARGET:
        return discover_projects_for_target(config), 1
    # SCOPE_ORG
    targets = discover_targets(config)
    projects = discover_projects_for_org(config)
    return projects, len(targets)


def _process_one(config: Config, project: Project) -> ProjectResult:
    """Run the existing SBOM workflow for a single project.

    Re-raises fatal errors (configuration/authentication). Non-fatal per-project
    errors are captured in the returned :class:`ProjectResult`.
    """
    logger = get_logger()
    project_config = replace(
        config,
        snyk_org_id=project.org_id,
        snyk_target_id=project.target_id,
        snyk_project_id=project.project_id,
    )
    start = time.perf_counter()
    try:
        result = SbomService(project_config).run()
    except SbomUnsupportedError as exc:
        elapsed = time.perf_counter() - start
        logger.info(
            "Project %s skipped: %s", project.project_id, exc.message
        )
        return ProjectResult(
            project=project,
            generated=False,
            uploaded=False,
            ok=False,
            skipped=True,
            elapsed_s=elapsed,
            error=exc.message,
        )
    except AppError as exc:
        if exc.exit_code in (ExitCode.CONFIG_ERROR, ExitCode.AUTH_FAILURE):
            raise  # fatal: abort the whole run
        elapsed = time.perf_counter() - start
        generated = exc.exit_code != ExitCode.SBOM_GENERATION_FAILURE
        logger.error("Project %s failed: %s", project.project_id, exc.message)
        return ProjectResult(
            project=project,
            generated=generated,
            uploaded=False,
            ok=False,
            elapsed_s=elapsed,
            error=exc.message,
        )

    elapsed = time.perf_counter() - start
    return ProjectResult(
        project=project,
        generated=True,
        uploaded=result.uploaded,
        ok=True,
        elapsed_s=elapsed,
    )


def run_scope(config: Config) -> ScopeSummary:
    """Discover and process all projects for the configured scope."""
    logger = get_logger()
    started = time.perf_counter()

    projects, targets_discovered = _discover(config)
    total = len(projects)
    logger.info(
        "Scope %s: discovered %d project(s)%s",
        config.snow_application_scope,
        total,
        f" across {targets_discovered} target(s)" if targets_discovered is not None else "",
    )

    results: list[ProjectResult] = []
    for index, project in enumerate(projects, start=1):
        logger.info(
            "Processing Project %d of %d | project=%s (%s) | target=%s",
            index,
            total,
            project.name,
            project.project_id,
            project.target_id or "-",
        )
        result = _process_one(config, project)
        if result.skipped:
            status = "SKIPPED (unsupported)"
        elif not result.ok:
            status = f"FAILED ({result.error})"
        elif config.api_dry_run:
            status = "OK (dry-run, upload skipped)"
        else:
            status = "OK"
        logger.info(
            "Result: %s | format=%s | elapsed=%.1fs",
            status,
            config.snyk_sbom_format,
            result.elapsed_s,
        )
        results.append(result)

    summary = ScopeSummary(
        scope=config.snow_application_scope,
        dry_run=config.api_dry_run,
        projects_discovered=total,
        sboms_generated=sum(1 for r in results if r.generated),
        succeeded=sum(1 for r in results if r.ok),
        skipped=sum(1 for r in results if r.skipped),
        failed=sum(1 for r in results if not r.ok and not r.skipped),
        elapsed_s=time.perf_counter() - started,
        targets_discovered=targets_discovered,
    )
    logger.info("%s", summary.format_report())
    return summary


# ═══════════════════════════════════════════════════════════════════════════
# CLI mode (SNYK_CLI): upload a Snyk-CLI-produced SBOM file
# ═══════════════════════════════════════════════════════════════════════════

def _validate_sbom_file(sbom_file_path: str | None) -> Path:
    """Validate the provided SBOM file path before any network call.

    Raises:
        ConfigError: if the path is missing, does not exist, is not a file, is
            empty, or is unreadable (exit code 1).
    """
    if not sbom_file_path:
        raise ConfigError(
            "SNYK_CLI mode requires --sbom-file-path.",
            operation="cli_mode",
            next_step="Provide the path to the Snyk CLI SBOM file: --sbom-file-path <file>.",
        )

    path = Path(sbom_file_path).expanduser()
    if not path.exists():
        raise ConfigError(
            f"SBOM file not found: {path}",
            operation="cli_mode",
            next_step="Provide an existing SBOM file path via --sbom-file-path.",
        )
    if not path.is_file():
        raise ConfigError(
            f"SBOM path is not a file: {path}",
            operation="cli_mode",
            next_step="Provide a path to a regular SBOM file, not a directory.",
        )
    try:
        size = path.stat().st_size
        with path.open("rb"):
            pass
    except OSError as exc:
        raise ConfigError(
            f"SBOM file is not readable: {path}",
            operation="cli_mode",
            parsed_message=str(exc),
            next_step="Verify file permissions for the SBOM file.",
        ) from exc
    if size == 0:
        raise ConfigError(
            f"SBOM file is empty: {path}",
            operation="cli_mode",
            next_step="Provide a non-empty SBOM file produced by the Snyk CLI.",
        )
    return path


def run_cli_upload(config: Config, sbom_file_path: str | None) -> int:
    """Validate and upload a Snyk CLI SBOM file to ServiceNow.

    Returns a process exit code (0 success, 1 config, 2 auth, 4 upload).
    """
    logger = get_logger()
    path = _validate_sbom_file(sbom_file_path)

    if config.api_dry_run:
        logger.warning("API_DRY_RUN is ignored in SNYK_CLI mode; proceeding with upload.")

    logger.info("Uploading Snyk CLI SBOM file: %s", path)
    try:
        ServiceNowClient(config).upload_sbom(path)
    except AppError as exc:
        logger.error("%s\n%s", exc.__class__.__name__, exc.format_report())
        return exc.exit_code

    logger.info("Complete: SBOM %s uploaded to ServiceNow.", path)
    return ExitCode.SUCCESS


# ═══════════════════════════════════════════════════════════════════════════
# Entry point
# ═══════════════════════════════════════════════════════════════════════════

def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="snyk_sbom_to_servicenow",
        description="Export a Snyk SBOM (API mode) or upload a Snyk CLI SBOM file, "
        "then push it to ServiceNow.",
    )
    parser.add_argument(
        "--sbom-file-path",
        dest="sbom_file_path",
        default=None,
        help="Path to the SBOM file to upload (required when RUN_MODE=SNYK_CLI).",
    )
    parser.add_argument(
        "--version",
        action="version",
        version=f"%(prog)s {__version__}",
    )
    return parser.parse_args(argv)


def run(argv: list[str] | None = None) -> int:
    """Execute the full workflow and return a process exit code."""
    args = _parse_args(argv)

    # Bootstrap logging at INFO until config tells us the desired level.
    logger = configure_logging("INFO")

    try:
        config = load_config()
    except AppError as exc:
        logger.error("Configuration error:\n%s", exc.format_report())
        return exc.exit_code

    logger = configure_logging(config.debug_level)
    if config.ssl_verify and not config.ca_bundle:
        enable_system_trust()

    try:
        if config.run_mode == MODE_CLI:
            logger.info("Starting SBOM upload (mode=SNYK_CLI)")
            return run_cli_upload(config, args.sbom_file_path)

        logger.info(
            "Starting SBOM export (mode=SNYK_API, scope=%s, org=%s, format=%s, api_dry_run=%s)",
            config.snow_application_scope,
            config.snyk_org_id,
            config.snyk_sbom_format,
            config.api_dry_run,
        )
        summary = run_scope(config)
    except AppError as exc:
        logger.error("%s\n%s", exc.__class__.__name__, exc.format_report())
        return exc.exit_code
    except Exception as exc:  # noqa: BLE001 - map any unexpected error to code 5
        logger.exception("Unexpected error: %s", exc)
        return ExitCode.UNEXPECTED

    return summary.exit_code


def main() -> None:
    sys.exit(run())


if __name__ == "__main__":
    main()
